### ISSUE TITLE
had this bug all of a sudden on forge 36.1.31 minecraft 1.16.5

### ISSUE THREAD

**Issue by Mr-Syntax** [TheIllusiveC4/Curios#156]
java.lang.NullPointerException
	at top.theillusivec4.curios.common.CuriosHelper.getCuriosHandler(CuriosHelper.java:67)
	at top.theillusivec4.curios.common.CuriosHelper.findEquippedCurio(CuriosHelper.java:106)
	at its_meow.betteranimalsplus.compat.curios.CuriosModCompat.lambda$subscribe$1(CuriosModCompat.java:33)
	at its_meow.betteranimalsplus.compat.curios.CuriosModCompat$$Lambda$16136/992134292.canEquip(Unknown Source)
	at its_meow.betteranimalsplus.common.item.ItemCape.canEquip(ItemCape.java:52)
	at net.minecraftforge.common.extensions.IForgeItemStack.canEquip(IForgeItemStack.java:313)
	at com.stereowalker.survive.client.events.TooltipEvents.tooltips(TooltipEvents.java:33)
	at net.minecraftforge.eventbus.ASMEventHandler_2224_TooltipEvents_tooltips_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2621/308316194.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:281)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:702)
	at net.minecraft.client.Minecraft.lambda$null$11(Minecraft.java:665)
	at net.minecraft.client.Minecraft$$Lambda$34416/1640064993.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:36)
	at net.minecraft.client.util.SearchTreeReloadable.func_217872_a(SourceFile:48)
	at net.minecraft.client.network.play.ClientPlayNetHandler$$Lambda$34414/1618470218.accept(Unknown Source)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1312)
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:27)
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15)
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34)
	at net.minecraft.network.PacketThreadUtil$$Lambda$34232/1873969372.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:130)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$497/149647258.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)

**Comment by TheIllusiveC4** [comment]
This looks like it may be caused by some other mods, namely Survive or Better Animals Plus. Please try and reproduce this issue with only Curios installed.
