### ISSUE TITLE
Index 49 out of bounds for length 46

### ISSUE THREAD

**Issue by LIMPIX31** [TheIllusiveC4/Curios#169]
* Curios: 1.16.5-4.0.5.2
* Forge: 1.16.5-forge-36.2.2
When logging into the server, I cannot access the Curios slots, however, when go into the nether and back, the slots start working, while the slots are not displayed I get the following error
```
[Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.IndexOutOfBoundsException: Index 49 out of bounds for length 46
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.minecraft.inventory.container.Container.func_75139_a(Container.java:150) ~[?:?]
	at net.minecraft.inventory.container.Container.func_75141_a(Container.java:448) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147266_a(ClientPlayNetHandler.java:1084) ~[?:?]
	at net.minecraft.network.play.server.SSetSlotPacket.func_148833_a(SourceFile:29) ~[?:?]
	at net.minecraft.network.play.server.SSetSlotPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2-launcher.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:53) [ForgeWrapper-1.5.2.jar:1.5.2]
```
List of used mods:
```
appliedEnergistics2
BetterDiving
BetterDungeons
BetterMineshafts
BetterStrongholds
ComputerCraft
CD4017BE
Chisel
corpse
The Create
Environmental Tech
Extreme Reactors 2
Flux Networks
Immersive Engineering
Industrial Foregoing
Iron Chest
Mekanism
More Minecarts
More Villagers
Powah
Quark
Redstone Control 2
Refined Pipes
Silent Gear
Simple Storage Network
Simply Jetpacks 2
Super Multi Drills
Thermal Series
Xaero's Map
```

**Comment by TheIllusiveC4** [comment]
Does this happen without Optifine? Moreover, does this happen with only Curios installed? If not, that's too many mods and you will need to trim it down in order to isolate the compatibility issue.
