### ISSUE TITLE
1.18.1 Server issue

### ISSUE THREAD

**Issue by LupusVentus** [TheIllusiveC4/Curios#216]
Hey there. Been trying to run your API on server, but got a crash. Would appreciate if you could help. Here's the code:

Crash Report UUID: bad55102-644c-4288-bef8-3d9f6e018807
        FML: 39.0
        Forge: net.minecraftforge:39.0.64[19:03:11] [Forge Version Check/INFO]: [mcwdoors] Found status: UP_TO_DATE Current: 1.0.5 Target: null
[19:03:11] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[19:03:11] [main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Curios API (curios) encountered an error during the process_imc event phase
з7java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/EntityRendererProvider
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:235) ~[fmlcore-1.18.1-39.0.64.jar%23134!/:?]
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.64.jar%23134!/:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:200) ~[fmlcore-1.18.1-39.0.64.jar%23134!/:?]
        at net.minecraftforge.fml.ModLoader.lambda$finishMods$17(ModLoader.java:189) ~[fmlcore-1.18.1-39.0.64.jar%23134!/:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:189) ~[fmlcore-1.18.1-39.0.64.jar%23134!/:?]
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:48) ~[forge-1.18.1-39.0.64-universal.jar%23137!/:?]
        at net.minecraft.server.Main.main(Main.java:104) ~[server-1.18.1-20211210.034407-srg.jar%23133!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.1-39.0.64.jar%2323!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

**Comment by LupusVentus** [comment]
Also, just thought that a Bug label was probably wrong for this one...

**Comment by TheIllusiveC4** [comment]
That's kinda weird. Does it work if you load up _only_ Curios?

**Comment by LupusVentus** [comment]
Nope. Trying to rebuild my modpack rn, maybe that will solve it

**Comment by LupusVentus** [comment]
Well, the problem magically solved itself once I rebuilt my modpack. So, sorry for bothering you, I guess.
