### ISSUE TITLE
Breaks BangeeCord connection (1.19.2)

### ISSUE THREAD

**Issue by vgrynch** [TheIllusiveC4/Curios#328]
When using Curios on the Forge server via BangeeCord, BangeeCord breaks the connection due to bad packets from the server. It appears either empty packets or wrong packets are sent. Adding just a lib without any mod using it also breaks. Please, fix it. (Mod was installed on both client and server, versions are the same, and Forge versions are also the same.)

Here is a log from the BangeeCord:

```
[14:44:23] [Netty Worker IO Thread #6/WARN]: [/XXXXXXXXXX:50430|XXXXXXXX] <-> DownstreamBridge <-> [lobby] - could not decode packet! java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 48
[14:44:23] [Netty Worker IO Thread #6/ERROR]: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 48
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 48
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:846)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:307)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:84)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[14:44:23] [Netty Worker IO Thread #6/ERROR]: 	... 24 more

```

**Comment by TheIllusiveC4** [comment]
I'm not really sure of the cause, but if this happens only with BungeeCord then you will likely need to report it to those developers instead. I'm also unsure if this is supposed to be a Forge environment or a hybrid one, due to the presence of plugins. Mixing mods and plugins could cause various issues that are hard to pinpoint and even harder to resolve.

I can only provide further support if this happens on a Forge server with only Curios and no plugins installed.
