### ISSUE TITLE
Error creative inventory

### ISSUE THREAD

**Issue by Sebz102030** [TheIllusiveC4/Curios#456]
### Minecraft Version

1.20.6

### What happened?

On server MohistMC curios API throws error when modern fix is present

Mod list:
![Screenshot_20241110_194256_Termux](https://github.com/user-attachments/assets/ad0e7840-a59d-48f5-84c5-2290ccc31b4e)

### How do you trigger this bug?

Install MohistMC on java 17
Install all mods from modlist above
Run server
Join server
Go in creative and open inventory

### Loader

Forge

### Loader Version

47.3.11

### Mod Version

5.11.0

### Relevant Log Outputs

---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-11-08 07:45:00
Description: Exception in server tick loop

net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file curios-server.toml of type SERVER for modid curios
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47) ~[fmlcore-1.20.1-47.3.11.jar%23279!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.20.1-47.3.11.jar%23279!/:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.3.11.jar%23279!/:?] {}
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?] {re:mixin}
	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.20.1-47.3.11.jar%23279!/:?] {}
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:96) ~[forge-1.20.1-47.3.11-universal.jar%23283!/:?] {re:classloading}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid character '
' after key [48]
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:152) ~[toml-3.6.4.jar%23108!/:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.4.jar%23108!/:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:88) ~[toml-3.6.4.jar%23108!/:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.4.jar%23108!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.4.jar%23107!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.4.jar%23107!/:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.4.jar%23107!/:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.4.jar%23107!/:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.4.jar%23107!/:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:43) ~[fmlcore-1.20.1-47.3.11.jar%23279!/:?] {}
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (aarch64) version Android-13
	Java Version: 21.0.1-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1493519992 bytes (1424 MiB) / 3607101440 bytes (3440 MiB) up to 3607101440 bytes (3440 MiB)
	CPUs: 8
	Processor Vendor: 0x53
	Processor Name: 
	Identifier: 0x53 Family 8 Model 0x004 Stepping r2p0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 3
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 6514.77
	Virtual memory used (MB): 8711.40
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 2423.52
	JVM Flags: 3 total; -Xms3440M -Xmx3440M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:kuma_api (incompatible), mod:exdeorum, mod:supermartijn642configlib (incompatible), mod:rechiseled (incompatible), mod:sophisticatedstorage (incompatible), mod:hammerlib, mod:projecte, mod:bigger_ae2, mod:sophisticatedcore (incompatible), mod:clumps (incompatible), mod:controlling (incompatible), mod:jei, mod:botanypots (incompatible), mod:mixinextras (incompatible), mod:bookshelf, mod:sophisticatedbackpacks (incompatible), mod:balm, mod:fusion, mod:fpsreducer, mod:cloth_config (incompatible), mod:forge, mod:slabstoblocks (incompatible), mod:refinedstorage, mod:athena, mod:craftingtweaks, mod:chipped (incompatible), mod:rechiseled_chipped (incompatible), mod:alltheores (incompatible), mod:glodium (incompatible), mod:exmachinis, mod:createstuffadditionsfix, mod:bcc (incompatible), mod:appliede (incompatible), mod:titanium (incompatible), mod:getittogetherdrops, mod:botanytrees (incompatible), mod:jade (incompatible), mod:ae2 (incompatible), mod:appflux (incompatible), mod:ironfurnaces, mod:rechiseledae2 (incompatible), mod:spectrelib (incompatible), mod:supermartijn642corelib, mod:solarflux (incompatible), mod:pipez, mod:curios (incompatible), mod:projectexpansion, mod:midnightlib (incompatible), mod:searchables (incompatible), mod:polymorph (incompatible), mod:fluxnetworks (incompatible), mod:teamprojecte, mod:framedblocks, mod:wlrs, mod:entityculling, mod:ftbultimine (incompatible), mod:resourcefullib (incompatible), mod:architectury (incompatible), mod:ae2wtlib (incompatible), mod:ftblibrary (incompatible), mod:megacells (incompatible), mod:appleskin (incompatible), mod:ferritecore (incompatible), mod:aiimprovements, mod:functionalstorage, mod:jadeaddons (incompatible), mod:refinedpolymorph, mod:polylib, mod:ftbbackups2 (incompatible), mod:codechickenlib (incompatible), mod:enderstorage (incompatible), SolarFlux, mod:placebo (incompatible), mod:powah (incompatible), mod:replantingcrops, mod:merequester (incompatible), mod:collective, mod:canary, mod:squatgrow (incompatible), mod:chunkloaders, mod:fastleafdecay, mod:toastcontrol (incompatible), mod:smoothboot, mod:elevatorid
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.20.1
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		kuma-api-forge-20.1.8+1.20.1.jar                  |KumaAPI                       |kuma_api                      |20.1.8              |DONE      |Manifest: NOSIGNATURE
		exdeorum-1.43.jar                                 |Ex Deorum                     |exdeorum                      |1.43                |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.20.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		rechiseled-1.1.6-forge-mc1.20.jar                 |Rechiseled                    |rechiseled                    |1.1.6               |DONE      |Manifest: NOSIGNATURE
		sophisticatedstorage-1.20.1-0.10.45.912.jar       |Sophisticated Storage         |sophisticatedstorage          |0.10.45.912         |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.20.0.105.jar                  |Just Enough Items             |jei                           |15.20.0.105         |DONE      |Manifest: NOSIGNATURE
		HammerLib-1.20.1-20.1.33.jar                      |HammerLib                     |hammerlib                     |20.1.33             |DONE      |Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		ProjectE-1.20.1-PE1.0.1.jar                       |ProjectE                      |projecte                      |1.0.1               |DONE      |Manifest: NOSIGNATURE
		bigger_ae2-1.20.1-1.3.5.jar                       |Bigger AE2                    |bigger_ae2                    |1.3.5               |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.20.1-0.6.34.718.jar           |Sophisticated Core            |sophisticatedcore             |0.6.34.718          |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.20.1-12.0.0.4.jar                  |Clumps                        |clumps                        |12.0.0.4            |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.20.1-12.0.2.jar               |Controlling                   |controlling                   |12.0.2              |DONE      |Manifest: NOSIGNATURE
		Placebo-1.20.1-8.6.2.jar                          |Placebo                       |placebo                       |8.6.2               |DONE      |Manifest: NOSIGNATURE
		Powah-5.0.7.jar                                   |Powah                         |powah                         |5.0.7               |DONE      |Manifest: NOSIGNATURE
		BotanyPots-Forge-1.20.1-13.0.39.jar               |BotanyPots                    |botanypots                    |13.0.39             |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-rc.4.jar                  |MixinExtras                   |mixinextras                   |0.2.0-rc.4          |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.2.13.jar                |Bookshelf                     |bookshelf                     |20.2.13             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.20.1-3.20.11.1115.jar    |Sophisticated Backpacks       |sophisticatedbackpacks        |3.20.11.1115        |DONE      |Manifest: NOSIGNATURE
		midnightlib-forge-1.4.2.jar                       |MidnightLib                   |midnightlib                   |1.4.2               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.3.9-all.jar                   |Balm                          |balm                          |7.3.9               |DONE      |Manifest: NOSIGNATURE
		ToastControl-1.20.1-8.0.3.jar                     |Toast Control                 |toastcontrol                  |8.0.3               |DONE      |Manifest: NOSIGNATURE
		fusion-1.1.1-forge-mc1.20.1.jar                   |Fusion                        |fusion                        |1.1.1               |DONE      |Manifest: NOSIGNATURE
		FpsReducer2-forge-1.20-2.5.jar                    |FPS Reducer                   |fpsreducer                    |1.20-2.5            |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.136-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.136            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.11-universal.jar                |Forge                         |forge                         |47.3.11             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		slabstoblocks-1.20.1-1-forge.jar                  |SlabsToBlocks                 |slabstoblocks                 |1.20.1-1-forge      |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.12.4.jar                         |Refined Storage               |refinedstorage                |1.12.4              |DONE      |Manifest: NOSIGNATURE
		athena-forge-1.20.1-3.1.2.jar                     |Athena                        |athena                        |3.1.2               |DONE      |Manifest: NOSIGNATURE
		replantingcrops-1.20.1-5.4.jar                    |Replanting Crops              |replantingcrops               |5.4                 |DONE      |Manifest: NOSIGNATURE
		craftingtweaks-forge-1.20.1-18.2.5.jar            |CraftingTweaks                |craftingtweaks                |18.2.5              |DONE      |Manifest: NOSIGNATURE
		chipped-forge-1.20.1-3.0.7.jar                    |Chipped                       |chipped                       |3.0.7               |DONE      |Manifest: NOSIGNATURE
		rechiseled_chipped-1.1.jar                        |Rechiseled: Chipped           |rechiseled_chipped            |1.1                 |DONE      |Manifest: NOSIGNATURE
		alltheores-1.20.1-47.1.3-2.2.4.jar                |AllTheOres                    |alltheores                    |2.2.4               |DONE      |Manifest: NOSIGNATURE
		Glodium-1.20-1.5-forge.jar                        |Glodium                       |glodium                       |1.20-1.5-forge      |DONE      |Manifest: NOSIGNATURE
		exmachinis-deorum-1.20.1-3.0.3.jar                |Ex Machinis: Divitiae Deorum  |exmachinis                    |3.0.3               |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		createstuffadditionsfix-forge-1.20.1-0.0.0.1.jar  |CreateStuffAdditionsFix       |createstuffadditionsfix       |0.0.0.1             |DONE      |Manifest: NOSIGNATURE
		BetterCompatibilityChecker-forge-4.0.8+mc1.20.1.ja|Better Compatibility Checker  |bcc                           |4.0.8               |DONE      |Manifest: NOSIGNATURE
		appliede-0.14.0.jar                               |AppliedE                      |appliede                      |0.14.0              |DONE      |Manifest: NOSIGNATURE
		titanium-1.20.1-3.8.32.jar                        |Titanium                      |titanium                      |3.8.32              |DONE      |Manifest: NOSIGNATURE
		getittogetherdrops-forge-1.20-1.3.jar             |Get It Together, Drops!       |getittogetherdrops            |1.3                 |DONE      |Manifest: NOSIGNATURE
		BotanyTrees-Forge-1.20.1-9.0.17.jar               |BotanyTrees                   |botanytrees                   |9.0.17              |DONE      |Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.11.1.jar                     |Jade                          |jade                          |11.11.1+forge       |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-forge-15.2.13.jar             |Applied Energistics 2         |ae2                           |15.2.13             |DONE      |Manifest: NOSIGNATURE
		AppliedFlux-1.20-1.1.9-forge.jar                  |AppliedFlux                   |appflux                       |1.20-1.1.9-forge    |DONE      |Manifest: NOSIGNATURE
		ironfurnaces-1.20.1-4.1.6.jar                     |Iron Furnaces                 |ironfurnaces                  |4.1.6               |DONE      |Manifest: NOSIGNATURE
		rechiseledae2-forge-1.20.1-1.0.0.jar              |Rechiseled: AE2               |rechiseledae2                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.13.15+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.15+1.20.1      |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.17a-forge-mc1.20.1.jar |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17+a            |DONE      |Manifest: NOSIGNATURE
		smoothboot(reloaded)-mc1.20.1-0.0.4.jar           |Smooth Boot (Reloaded)        |smoothboot                    |0.0.4               |DONE      |Manifest: NOSIGNATURE
		merequester-forge-1.20.1-1.1.5.jar                |ME Requester                  |merequester                   |1.20.1-1.1.5        |DONE      |Manifest: NOSIGNATURE
		SolarFluxReborn-1.20.1-20.1.6.jar                 |Solar Flux Reborn             |solarflux                     |20.1.6              |DONE      |Manifest: 97:e8:52:e9:b3:f0:1b:83:57:4e:83:15:f7:e7:76:51:c6:60:5f:2b:45:59:19:a7:31:9e:98:69:56:4f:01:3c
		pipez-forge-1.20.1-1.2.16.jar                     |Pipez                         |pipez                         |1.20.1-1.2.16       |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.11.0+1.20.1.jar                    |Curios API                    |curios                        |5.11.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		ProjectExpansion-1.20.1-1.1.2.jar                 |Project Expansion             |projectexpansion              |1.20.1-1.1.2        |DONE      |Manifest: 16:32:1c:48:e2:f7:71:f1:1b:23:7f:74:d8:e6:89:43:6a:a8:33:8f:49:17:6a:11:19:cd:66:4b:88:c1:02:19
		collective-1.20.1-7.87.jar                        |Collective                    |collective                    |7.87                |DONE      |Manifest: NOSIGNATURE
		Searchables-forge-1.20.1-1.0.3.jar                |Searchables                   |searchables                   |1.0.3               |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.49.5+1.20.1.jar                 |Polymorph                     |polymorph                     |0.49.5+1.20.1       |DONE      |Manifest: NOSIGNATURE
		refinedpolymorph-0.1.1-1.20.1.jar                 |Refined Polymorphism          |refinedpolymorph              |0.1.1-1.20.1        |DONE      |Manifest: NOSIGNATURE
		FluxNetworks-1.20.1-7.2.1.15.jar                  |Flux Networks                 |fluxnetworks                  |7.2.1.15            |DONE      |Manifest: NOSIGNATURE
		teamprojecte-1.20.1-1.1.4.jar                     |Team ProjectE                 |teamprojecte                  |1.1.4               |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-9.3.1.jar                            |FramedBlocks                  |framedblocks                  |9.3.1               |DONE      |Manifest: NOSIGNATURE
		wlrs-1.14.2-1.20.1.jar                            |Waterlogged Redstone          |wlrs                          |1.14.2-1.20.1       |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.7.0-mc1.20.1.jar            |EntityCulling                 |entityculling                 |1.7.0               |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.20.1-lex-1.9.jar                     |Elevator Mod                  |elevatorid                    |1.20.1-lex-1.9      |DONE      |Manifest: NOSIGNATURE
		canary-mc1.20.1-0.3.3.jar                         |Canary                        |canary                        |0.3.3               |DONE      |Manifest: NOSIGNATURE
		ftb-ultimine-forge-2001.1.5.jar                   |FTB Ultimine                  |ftbultimine                   |2001.1.5            |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.29.jar            |Resourceful Lib               |resourcefullib                |2.1.29              |DONE      |Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |DONE      |Manifest: NOSIGNATURE
		ae2wtlib-15.2.3-forge.jar                         |AE2WTLib                      |ae2wtlib                      |15.2.3-forge        |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-2001.2.4.jar                    |FTB Library                   |ftblibrary                    |2001.2.4            |DONE      |Manifest: NOSIGNATURE
		squatgrow-forge-5.3.0+mc1.20.1.jar                |Squat Grow                    |squatgrow                     |5.3.0+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		megacells-forge-2.4.4-1.20.1.jar                  |MEGA Cells                    |megacells                     |2.4.4-1.20.1        |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		ferritecore-6.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |6.0.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		AI-Improvements-1.20-0.5.2.jar                    |AI-Improvements               |aiimprovements                |0.5.2               |DONE      |Manifest: NOSIGNATURE
		functionalstorage-1.20.1-1.2.10.jar               |Functional Storage            |functionalstorage             |1.20.1-1.2.10       |DONE      |Manifest: NOSIGNATURE
		chunkloaders-1.2.8a-forge-mc1.20.1.jar            |Chunk Loaders                 |chunkloaders                  |1.2.8a              |DONE      |Manifest: NOSIGNATURE
		JadeAddons-1.20.1-Forge-5.3.1.jar                 |Jade Addons                   |jadeaddons                    |5.3.1+forge         |DONE      |Manifest: NOSIGNATURE
		polylib-forge-2000.0.3-build.143.jar              |PolyLib                       |polylib                       |2000.0.3-build.143  |DONE      |Manifest: NOSIGNATURE
		ftbbackups2-forge-1.20-1.0.23.jar                 |FTB Backups 2                 |ftbbackups2                   |1.0.23              |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-32.jar                              |Fast Leaf Decay               |fastleafdecay                 |32                  |DONE      |Manifest: NOSIGNATURE
		CodeChickenLib-1.20.1-4.4.0.516-universal.jar     |CodeChicken Lib               |codechickenlib                |4.4.0.516           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.20.1-2.11.0.188-universal.jar      |EnderStorage                  |enderstorage                  |2.11.0.188          |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
	Crash Report UUID: 7ab827c9-3387-44fb-a99e-5fecb805db56
	FML: 47.3
	Forge: net.minecraftforge:47.3.11

**Comment by TheIllusiveC4** [comment]
Mohist servers are unsupported unless the same issue can be reproduced in a purely Forge/NeoForge environment.
