### ISSUE TITLE
Crash on launch MC 1.16.2 fabric curios 0.0.6

### ISSUE THREAD

**Issue by crest1993** [TheIllusiveC4/Curios#66]
Already tried trial and error with each mod, and this is the crash report i get

`---- Minecraft Crash Report ----
// Why did you do that?

Time: 8/20/20 12:26 AM
Description: Initializing game

net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'rpgstats'
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:251)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.NoClassDefFoundError: dev/onyxstudios/cca/api/v3/util/PlayerComponent
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:156)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at mc.rpgstats.main.RPGStats.<clinit>(RPGStats.java:34)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186)
	... 13 more
Caused by: java.lang.ClassNotFoundException: dev.onyxstudios.cca.api.v3.util.PlayerComponent
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 30 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193)
	at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:251)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 71468584 bytes (68 MB) / 339169280 bytes (323 MB) up to 2112618496 bytes (2014 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx2048M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Fabric Mods: 
		allure: Allure 1.2.3
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		antighost: AntiGhost 1.16.2-fabric0.17.2-1.1.2
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		autoharvest: autoharvest 1.0.4
		bebooks: Better Enchanted Books 1.1.1
		beenfo: Beenfo 1.16.2-fabric0.17.2-1.1.1
		better_mod_button: Better Mod Button 1.1.4
		betterf3: BetterF3 1.1.1
		bettergraves: Better Graves 0.3.0
		betterthanmending: BetterThanMending 1.2.0
		blue_endless_jankson: jankson +
		cardinal-components-base: Cardinal Components API (base) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-entity: Cardinal Components API (entities) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-item: Cardinal Components API (items) 2.5.0-nightly.1.16.2-rc2
		chainmail: Chainmail 0.4.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.8
		cloth-config2: Cloth Config v4 4.7.0-unstable
		cmdkeybind: Command Macros 1.4.4-1.16
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		couplings: Couplings 1.3.1
		curios: Curios API 0.0.6-1.16.2
		customskinloader: CustomSkinLoader 14.12-SNAPSHOT-157
		dark-loading-screen: Dark Loading Screen 1.4.1
		diggusmaximus: Diggus Maximus 1.3.1-1.16
		dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
		easiercrafting: EasierCrafting 1.16.2-fabric0.17.2-1.6.3
		easiervillagertrading: EasierVillagerTrading 1.16.2-fabric0.17.2-1.5.2
		enchantedtooltips: Enchanted ToolTips 1.3.3-1.16
		expandedstorage: ExpandedStorage 5.4.20
		fabric: Fabric API 0.18.0+build.397-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b4e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+84cce57fd2
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+02fb8fda4e
		fabricloader: Fabric Loader 0.9.1+build.205
		fastfurnace: FastFurnace 2.2
		fatxporbs: Fat Experience Orbs 0.0.7
		fiber: fiber 0.23.0-2
		gamemodeoverhaul: GamemodeOverhaul 1.16.1-1.0.1.8
		gbfabrictools: GBfabrictools 1.2.2+1.16.2
		infinityfix: Infinity Fix 1.1.0
		inventorysorter: Inventory Sorter 1.7.2-1.16
		jankson: Jankson 3.0.1+j1.2.0
		kyrptconfig: Kytpt Config 1.1.2-1.16
		libcd: LibCapableData 3.0.2+1.16.2
		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
		libstructure: LibStructure 1.5
		limitless: limitless 0.2.0
		linkedstorage: Linked Storage 1.3.5-1.16
		magna: Magna 1.4.0-1.16.2
		maybe-data: Maybe data 1.0.0-1.16.2
		minecraft: Minecraft 1.16.2
		modmenu: Mod Menu 1.14.6+build.31
		modupdater: ModUpdater 1.1.11+1.16.2-rc2
		moretotems: More Totems 2.6.0
		mtca: More Totems Curios Addon 1.0.1
		nomadbooks: Nomad Books 0.5.5
		okzoomer: Ok Zoomer 4.0.0+1.16.2
		randomconfigs: RandomConfigs 1.16.2-1.4.2.2-fabric
		reborncore: Reborn Core 4.4.0+build.67
		repurposed_structures: Repurposed Structures 1.5.0
		respawnablepets: Respawnable Pets 6
		ring_of_attraction: Ring Of Attraction 1.0.22
		ring_of_enderchest: Ring of Enderchest 1.0.22
		ring_of_growth: Ring Of Growth 1.0.20
		ring_of_miner: Ring Of Miner 1.0.17
		roughlyenoughitems: Roughly Enough Items 5.2.3
		roughlyenoughitems-api: REI (API) 5.2.3
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.2.3
		roughlyenoughitems-runtime: REI (Runtime) 5.2.3
		rpgstats: RPGStats 2.1.3+1.16.2
		sheepconsistency: Sheep Consistency 1.0.2
		simple_backpack: SimpleBackpack 1.0.27
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		strongandfairanvils: Strong and Fair Anvils 0.3.0+1.16
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.5.1+build.101
		trapexpansion: Trap Expansion 1.3.2
		trees-do-not-float: Trees Do Not Float 1.12.94
		trinkets: Trinkets 2.6.4
		vanilla-hammers: Vanilla Hammers 2.0.5-1.16.2
		vanillaautomated: Vanilla Automated 1.1.3
		voxelmap: VoxelMap 1.10.10
		waila: Hwyla 1.9.22
		ward_blocks: Ward Blocks 1.0.15
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		worldtime: WorldTime 1.16.2-fabric0.17.2-1.2.4
		xradiation: X-radiation 0.0.1
	Launched Version: fabric-loader-0.9.1+build.205-1.16.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>`

**Comment by TheIllusiveC4** [comment]
> net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'rpgstats'

It looks like this isn't a Curios issue. It's caused by some mod with the id `rpgstats`.
